### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by cnutenor** [mspellecacy/map-canvas#1]
The idea its fantastic but The option to put the google maps api key does not appear anywhere, I have tried in foundry 0.89, sandbox system 0.10.1 and D & D5ed 1.5.2.

**Comment by mspellecacy** [comment]
Where are you looking? There should be a 'generic module settings' under the "Module Settings" tab.
Example from my running instance via The Forge: 
![image](https://user-images.githubusercontent.com/945839/137635055-9220025a-f9eb-4e05-a350-c955e6fb69aa.png)
If that isn't appearing for you, I'm not sure. If you can provide perhaps an error log from dev tools that might prove helpful. And thank you for trying my Module! 😄

**Comment by mspellecacy** [comment]
After speaking with @cnutenor via Discord the issue was traced back to the module relying on the "canvasReady" hook event. If there is no scene in the current world the registration never happens resulting in no settings being available.

Current Workaround: 
Create a new scene in your world and open it. This will trigger the hook and register the settings. Everything should now work as intended.
