### ISSUE TITLE
Stopped working. Needs update for new foundry version.

### ISSUE THREAD

**Issue by CrackerHax** [mspellecacy/map-canvas#13]
Stopped working. Says it last worked with foundry v11.

**Comment by mspellecacy** [comment]
This is a result of the recent pollyfill.io drama (and the domain disappearing). 

The fix is-

replacing: 
https://github.com/mspellecacy/map-canvas/blob/bed55cadcd843ee8ffd66846157b1f00c0474bfd/modules/map-canvas.js#L26

with:
`
await $.getScript('https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=default', () => {});
`

I'll try to get a fix out later today. If you need the fix immediately you can update the appropriate line in the module until then. 

Cheers,
Michael

**Comment by mspellecacy** [comment]
Should be resolved by PR https://github.com/mspellecacy/map-canvas/pull/14.

Let me know if this doesn't resolve your issues.

Cheers,
Michael
